version: '3.9'

services:
  flight_scraping:
    build: .
    container_name: flight_scraping_container
    ports:
      - "8080:8080"  # Puedes cambiar el puerto según tu necesidad
    volumes:
      - .:/flight_scraping  # Monta el directorio actual en el contenedor
    command: python ./scraping_web.py